# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
storageSpec:
  volumeClaimTemplate:
    spec:
      storageClassName: longhorn
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 50Gi
    selector: {}

grafana:
  defaultDashboardsTimezone: "America/New_York"
  plugins:
   - digrich-bubblechart-panel
   - grafana-clock-panel
   - grafana-piechart-panel
   - briangann-gauge-panel
   - jdbranham-diagram-panel
  additionalDataSources: 
    - name: loki
      access: proxy
      orgId: 1
      type: loki
      url: http://loki:3100
      version: 1
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: true
          editable: false
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      traefik2:
        gnetId: 12250
        revision: 1
        datasource: Prometheus
