# https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-monitoring/100.1.3%2Bup19.0.3/values.yaml
prometheus:
  prometheusSpec:
    evaluationInterval: 1m
    retentionSize: 50GiB
    scrapeInterval: 1m
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

grafana:
  persistence:
    accessModes:
      - ReadWriteOnce
    storageClassName: longhorn
    size: 50Gi
    subPath: null
    type: pvc
    annotations: null
    finalizers: null
    enabled: true
  defaultDashboardsTimezone: "America/New_York"
  plugins:
   - digrich-bubblechart-panel
   - grafana-clock-panel
   - grafana-piechart-panel
   - briangann-gauge-panel
   - jdbranham-diagram-panel
   - redis-datasource
  additionalDataSources: 
    - name: loki
      access: proxy
      orgId: 1
      type: loki
      url: http://loki:3100
      version: 1
      editable: true
    - name: redis
      access: proxy
      orgId: 1
      type: redis-datasource
      url: redis://redis-master.redis:6379
      jsonData:
        poolSize: 5
        timeout: 10
        pingInterval: 0
        pipelineWindow: 0
      version: 1
      editable: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: true
          editable: false
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      redis:
        gnetId: 12776
        revision: 2
        datasource: redis
      traefik2:
        gnetId: 12250
        revision: 1
        datasource: Prometheus

rke2ControllerManager:
  enabled: true

rke2Etcd:
  enabled: true

rke2Proxy:
  enabled: true

rke2Scheduler:
  enabled: true