apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${rancher_hostname}
spec:
  dnsNames:
    - ${rancher_hostname}
  secretName: tls-rancher-ingress
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
---
# Redirect to https
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: http-to-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rancher-route-redirect
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`${rancher_hostname}`)
      kind: Rule
      services:
      - name: noop@internal
        kind: TraefikService
      middlewares:
      - name: http-to-https
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rancher-route
spec:
  entryPoints:
    - websecure
  tls:
    secretName: tls-rancher-ingress
  routes:
    - match: Host(`${rancher_hostname}`)
      kind: Rule
      services:
      - name: rancher
        passHostHeader: true
        port: 80
