# https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml

auth:
  enabled: false
  sentinel: false

master:
  nodeSelector:
    kubernetes.io/os: linux
  persistence:
    storageClass: longhorn
    size: 5Gi

replica:
  nodeSelector:
    kubernetes.io/os: linux
  persistence:
    storageClass: longhorn
    size: 5Gi