# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml

deployment:
  kind: DaemonSet

dashboard:
  enabled: true

service:
  spec:
    externalTrafficPolicy: Local

nodeSelector:
  kubernetes.io/os: linux

providers:
  kubernetesIngress:
    ingressClass: traefik

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets: [0.100000, 0.300000, 1.200000, 5.000000]

# tolerations:
# - key: "CriticalAddonsOnly"
#   operator: "Equal"
#   value: "true"
#   effect: "NoSchedule"

  # volumes:
#   - name: ingress-certs
#     mountPath: "/certs"
#     type: configMap