# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml

deployment:
  kind: DaemonSet
  podLabels:
    app: traefik
  additionalContainers:
  - name: ts-sidecar
    imagePullPolicy: Always
    image: "ghcr.io/tailscale/tailscale:latest"
    env:
    # Store the state in a k8s secret
    # - name: TS_KUBE_SECRET
    #  value: "tailscale"
    - name: KUBERNETES_SERVICE_HOST
      value: ""
    - name: TS_USERSPACE
      value: "false"
    - name: TS_ACCEPT_DNS
      value: "true"
    - name: TS_AUTH_KEY
      valueFrom:
        secretKeyRef:
          name: tailscale-auth
          key: AUTH_KEY
          optional: true
    - name: TS_EXTRA_ARGS
      value: "--snat-subnet-routes=true"
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
    livenessProbe:
      exec:
        command:
        - wget
        - https://hello.ts.net/healthz
      initialDelaySeconds: 5
      periodSeconds: 600


dashboard:
  enabled: true

nodeSelector:
  kubernetes.io/os: linux

providers:
  kubernetesIngress:
    ingressClass: traefik

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
    entryPoint: metrics
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
      - 10.0

# tolerations:
# - key: "CriticalAddonsOnly"
#   operator: "Equal"
#   value: "true"
#   effect: "NoSchedule"

  # volumes:
#   - name: ingress-certs
#     mountPath: "/certs"
#     type: configMap