# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml

deployment:
  kind: DaemonSet
  podLabels:
    app: traefik
  additionalContainers:
  - name: ts-sidecar
    imagePullPolicy: Always
    image: "baristalabs/tailscale-k8s:latest"
    env:
      # Store the state in a k8s secret
    - name: KUBE_SECRET
      value: "tailscale"
    - name: USERSPACE
      value: "false"
    - name: AUTH_KEY
      valueFrom:
        secretKeyRef:
          name: tailscale-auth
          key: AUTH_KEY
          optional: true
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
    livenessProbe:
      exec:
        command:
        - wget
        - https://hello.ts.net/healthz
      initialDelaySeconds: 10
      periodSeconds: 600


dashboard:
  enabled: true

service:
  spec:
    externalTrafficPolicy: Local

nodeSelector:
  kubernetes.io/os: linux

providers:
  kubernetesIngress:
    ingressClass: traefik

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
    entryPoint: metrics
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
      - 10.0

# tolerations:
# - key: "CriticalAddonsOnly"
#   operator: "Equal"
#   value: "true"
#   effect: "NoSchedule"

  # volumes:
#   - name: ingress-certs
#     mountPath: "/certs"
#     type: configMap