# https://github.com/coredns/helm/blob/master/charts/coredns/values.yaml

serviceType: "LoadBalancer"

service:
  annotations:
    # Use an internal Azure Load Balancer
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  loadBalancerIP: 10.10.3.100

isClusterService: false

servers:
- zones:
  - zone: .
  port: 53
  plugins:
  - name: errors
  # Serves a /health endpoint on :8080, required for livenessProbe
  - name: health
    configBlock: |-
      lameduck 5s
  # Serves a /ready endpoint on :8181, required for readinessProbe
  - name: ready
  # Serves a /metrics endpoint on :9153, required for serviceMonitor
  - name: prometheus
    parameters: 0.0.0.0:9153
  - name: forward
    parameters: . 1.1.1.1
  - name: cache
    parameters: 30
  - name: loop
  - name: reload
  - name: loadbalance
- zones:
  - zone: baristalabs
    scheme: dns://
    use_tcp: false
  port: 53
  plugins:
  - name: file
    parameters: /etc/coredns/baristalabs-internal.db

zoneFiles:
 - filename: baristalabs-internal.db
   domain: baristalabs
   contents: |
     baristalabs.   IN SOA sns.dns.icann.com. noc.dns.icann.com. 2015082541 7200 3600 1209600 3600
     baristalabs.   IN NS  b.iana-servers.net.
     baristalabs.   IN NS  a.iana-servers.net.
     baristalabs.   IN A   100.80.73.93
     baristalabs.   IN A   100.98.77.13
     baristalabs.   IN A   100.66.78.81
     *.baristalabs. IN A   100.80.73.93
     *.baristalabs. IN A   100.98.77.13
     *.baristalabs. IN A   100.66.78.81
