# https://github.com/coredns/helm/blob/master/charts/coredns/values.yaml

serviceType: "LoadBalancer"

service:
  annotations:
    # Use an internal Azure Load Balancer
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  loadBalancerIP: 10.10.3.100

isClusterService: false
replicaCount: 2

servers:
- zones:
  - zone: .
  port: 53
  plugins:
  - name: errors
  # Serves a /health endpoint on :8080, required for livenessProbe
  - name: health
    configBlock: |-
      lameduck 5s
  # Serves a /ready endpoint on :8181, required for readinessProbe
  - name: ready
  # Serves a /metrics endpoint on :9153, required for serviceMonitor
  - name: prometheus
    parameters: 0.0.0.0:9153
  - name: forward
    parameters: . 1.1.1.1
  - name: cache
    parameters: 30
  - name: loop
  - name: reload
  - name: loadbalance
- zones:
  - zone: espresso.local
    scheme: dns://
    use_tcp: false
  port: 53
  plugins:
  - name: loadbalance
    parameters: round_robin
  - name: file
    parameters: /etc/coredns/espresso-local.db
  - name: forward
    parameters: . 1.1.1.1 1.0.0.1 8.8.8.8 8.8.4.4
  - name: cache
    parameters: 30
  - name: loop
  - name: reload

zoneFiles:
 - filename: espresso-local.db
   domain: espresso.local
   contents: |
     espresso.local.   IN SOA sns.dns.icann.com. noc.dns.icann.com. 2015082541 7200 3600 1209600 3600
     espresso.local.   IN NS  b.iana-servers.net.
     espresso.local.   IN NS  a.iana-servers.net.
     espresso.local.   IN A   100.80.73.93
     espresso.local.   IN A   100.98.77.13
     espresso.local.   IN A   100.66.78.81
     *.espresso.local. IN A   100.80.73.93
     *.espresso.local. IN A   100.98.77.13
     *.espresso.local. IN A   100.66.78.81
