apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name:  traefik
  labels:
    app: traefik
    release: prometheus-stack
spec:
  jobLabel: traefik-metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: ${TRAEFIK_INSTANCE}
      app.kubernetes.io/name: traefik
  namespaceSelector:
    matchNames:
      - ${TRAEFIK_NAMESPACE}
  podMetricsEndpoints:
    - port: metrics
      scheme: http
      path: /metrics